// <auto-generated />
namespace MyCompanyName.AbpZeroTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADD_CLOUMN_USERID_CARDINGO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD_CLOUMN_USERID_CARDINGO));
        
        string IMigrationMetadata.Id
        {
            get { return "201907290752053_ADD_CLOUMN_USERID_CARDINGO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
